namespace BrassTask.Api.Infrastructure.Validation;

// https://datatracker.ietf.org/doc/html/rfc7807
public class ProblemDetail
{
    /// <summary>
    /// A URI reference that identifies the problem type.
    /// </summary>
    public virtual string? Type { get; set; }

    /// <summary>
    /// A short, human-readable summary of the problem type.
    /// </summary>
    public virtual string Title { get; set; } = string.Empty;

    /// <summary>
    /// The HTTP status code generated by the origin server for this occurrence of the problem.
    /// </summary>
    public virtual int Status { get; set; }

    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    public string? Detail { get; set; }

    /// <summary>
    /// A URI reference that identifies the specific occurrence of the problem.
    /// </summary>
    public string? Instance { get; set; }
}
